CREATE TABLE IF NOT EXISTS config (
    config_key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS external_endpoints (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_label TEXT NOT NULL DEFAULT '',
    protocol TEXT NOT NULL DEFAULT 'openai',
    base_url TEXT NOT NULL DEFAULT '',
    api_key_enc TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    capabilities TEXT,
    subsystem_map TEXT,
    available_models TEXT,
    models_metadata TEXT,
    default_model TEXT,
    probe_status TEXT NOT NULL DEFAULT 'never',
    last_probe_at TIMESTAMPTZ,
    extra_config TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_external_endpoints_enabled ON external_endpoints (enabled);
CREATE INDEX IF NOT EXISTS idx_external_endpoints_protocol ON external_endpoints (protocol);

CREATE TABLE IF NOT EXISTS chat_history_cache (
    id BIGSERIAL PRIMARY KEY,
    interface_path TEXT NOT NULL,
    sender_name TEXT,
    sender_id TEXT,
    message_text TEXT NOT NULL,
    metadata TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (interface_path, timestamp)
);
CREATE INDEX IF NOT EXISTS idx_chat_history_cache_interface_path ON chat_history_cache (interface_path);
CREATE INDEX IF NOT EXISTS idx_chat_history_cache_timestamp ON chat_history_cache (timestamp DESC);

CREATE TABLE IF NOT EXISTS chat_session_meta (
    interface_path TEXT PRIMARY KEY,
    meta TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chat_session_meta_updated_at ON chat_session_meta (updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_archives (
    id TEXT PRIMARY KEY,
    session_id TEXT,
    name TEXT,
    messages TEXT NOT NULL,
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chat_archives_session ON chat_archives (session_id);
CREATE INDEX IF NOT EXISTS idx_chat_archives_created_at ON chat_archives (created_at DESC);

CREATE TABLE IF NOT EXISTS ai_diary (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    personal_thought TEXT,
    emotions TEXT DEFAULT '[]',
    interaction_summary TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interface TEXT,
    chat_id TEXT,
    thread_id TEXT,
    user_message TEXT,
    context_tags TEXT DEFAULT '[]',
    involved_users TEXT DEFAULT '[]'
);
CREATE INDEX IF NOT EXISTS idx_ai_diary_timestamp ON ai_diary (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ai_diary_interface_chat ON ai_diary (interface, chat_id);

CREATE TABLE IF NOT EXISTS ai_diary_archive (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    personal_thought TEXT,
    emotions TEXT DEFAULT '[]',
    interaction_summary TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interface TEXT,
    chat_id TEXT,
    thread_id TEXT,
    user_message TEXT,
    context_tags TEXT DEFAULT '[]',
    involved_users TEXT DEFAULT '[]'
);
CREATE INDEX IF NOT EXISTS idx_ai_diary_archive_timestamp ON ai_diary_archive (timestamp DESC);

CREATE TABLE IF NOT EXISTS memories (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    content TEXT NOT NULL,
    author TEXT,
    source TEXT,
    tags TEXT,
    scope TEXT,
    emotion TEXT,
    intensity INTEGER,
    emotion_state TEXT
);
CREATE INDEX IF NOT EXISTS idx_memories_timestamp ON memories (timestamp DESC);

CREATE TABLE IF NOT EXISTS emotion_state (
    id BIGSERIAL PRIMARY KEY,
    emotion_name TEXT NOT NULL,
    intensity DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_emotion_state_name ON emotion_state (emotion_name);
CREATE INDEX IF NOT EXISTS idx_emotion_state_timestamp ON emotion_state (timestamp DESC);

CREATE SEQUENCE IF NOT EXISTS emotion_diary_id_seq;
CREATE TABLE IF NOT EXISTS emotion_diary (
    id TEXT PRIMARY KEY DEFAULT ('emotion_' || nextval('emotion_diary_id_seq')::text),
    legacy_numeric_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    source TEXT,
    event TEXT,
    emotion TEXT,
    intensity DOUBLE PRECISION,
    state TEXT,
    trigger_condition TEXT,
    decision_logic TEXT,
    next_check TIMESTAMPTZ,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_emotion_diary_timestamp ON emotion_diary (timestamp DESC);

CREATE TABLE IF NOT EXISTS bio (
    id TEXT PRIMARY KEY,
    known_as TEXT DEFAULT '[]',
    likes TEXT DEFAULT '[]',
    not_likes TEXT DEFAULT '[]',
    information TEXT DEFAULT '',
    past_events TEXT DEFAULT '[]',
    feelings TEXT DEFAULT '[]',
    contacts TEXT DEFAULT '{}',
    social_accounts TEXT DEFAULT '[]',
    privacy TEXT DEFAULT 'default',
    created_at TEXT,
    last_accessed TEXT,
    last_update TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_count INTEGER DEFAULT 0,
    user_name TEXT
);

CREATE TABLE IF NOT EXISTS recent_chats (
    chat_id TEXT PRIMARY KEY,
    last_active DOUBLE PRECISION NOT NULL,
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_recent_chats_last_active ON recent_chats (last_active DESC);

CREATE TABLE IF NOT EXISTS scheduled_events (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    time TIME DEFAULT '00:00',
    recurrence_type TEXT DEFAULT 'none',
    next_run TIMESTAMPTZ NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered BOOLEAN DEFAULT FALSE,
    created_by TEXT DEFAULT 'synth',
    uid TEXT,
    rrule TEXT,
    tzid TEXT,
    source TEXT DEFAULT 'synth'
);
CREATE INDEX IF NOT EXISTS idx_scheduled_events_next_run ON scheduled_events (next_run);

CREATE TABLE IF NOT EXISTS blocklist (
    user_id BIGINT PRIMARY KEY,
    reason TEXT,
    blocked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chatlink (
    int_id BIGSERIAL PRIMARY KEY,
    interface TEXT NOT NULL,
    chat_id TEXT NOT NULL,
    thread_id TEXT,
    chat_name TEXT,
    message_thread_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (interface, chat_id)
);

CREATE TABLE IF NOT EXISTS message_map (
    trainer_message_id INTEGER PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    message_id INTEGER NOT NULL,
    timestamp DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS grillo_beats (
    id BIGSERIAL PRIMARY KEY,
    beat_type TEXT NOT NULL,
    next_beat TIMESTAMPTZ NOT NULL,
    metadata TEXT,
    enabled BOOLEAN DEFAULT TRUE,
    plugin_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_grillo_beats_next_beat ON grillo_beats (next_beat, enabled, plugin_enabled);
CREATE INDEX IF NOT EXISTS idx_grillo_beats_type ON grillo_beats (beat_type);

CREATE TABLE IF NOT EXISTS grillo_activity_log (
    id BIGSERIAL PRIMARY KEY,
    beat_type TEXT NOT NULL,
    prompt_text TEXT NOT NULL,
    response_text TEXT,
    diary_entry_id BIGINT REFERENCES ai_diary(id) ON DELETE SET NULL,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata TEXT,
    suppressed_count INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_grillo_activity_log_executed_at ON grillo_activity_log (executed_at DESC);
CREATE INDEX IF NOT EXISTS idx_grillo_activity_log_type ON grillo_activity_log (beat_type);

CREATE TABLE IF NOT EXISTS grillo_action_execs (
    id BIGSERIAL PRIMARY KEY,
    activity_log_id BIGINT NOT NULL REFERENCES grillo_activity_log(id) ON DELETE CASCADE,
    action_index INTEGER NOT NULL,
    action_type TEXT NOT NULL,
    payload TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processed', 'failed')),
    error_text TEXT,
    result TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_grillo_action_execs_activity_log_id ON grillo_action_execs (activity_log_id);

CREATE TABLE IF NOT EXISTS agent_activity_log (
    id BIGSERIAL PRIMARY KEY,
    command TEXT NOT NULL,
    proposer TEXT,
    status TEXT NOT NULL DEFAULT 'proposed' CHECK (status IN ('proposed', 'approved', 'rejected', 'executed', 'cancelled')),
    trainer_id TEXT,
    request_ts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response_ts TIMESTAMPTZ,
    result TEXT,
    metadata TEXT
);
CREATE INDEX IF NOT EXISTS idx_agent_activity_log_status ON agent_activity_log (status);
CREATE INDEX IF NOT EXISTS idx_agent_activity_log_proposer ON agent_activity_log (proposer);

CREATE TABLE IF NOT EXISTS agent_action_execs (
    id BIGSERIAL PRIMARY KEY,
    activity_log_id BIGINT NOT NULL REFERENCES agent_activity_log(id) ON DELETE CASCADE,
    command TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'failed')),
    error_text TEXT,
    result TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_agent_action_execs_activity_log_id ON agent_action_execs (activity_log_id);

CREATE TABLE IF NOT EXISTS agent_tasks (
    id BIGSERIAL PRIMARY KEY,
    engine TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'waiting_for_approval', 'paused', 'completed', 'failed', 'cancelled')),
    input TEXT,
    iterations_meta TEXT,
    output TEXT,
    trainer_id TEXT,
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_agent_tasks_status ON agent_tasks (status);
CREATE INDEX IF NOT EXISTS idx_agent_tasks_created_at ON agent_tasks (created_at DESC);

CREATE TABLE IF NOT EXISTS message_logs (
    id BIGSERIAL PRIMARY KEY,
    chat_id TEXT NOT NULL,
    interface TEXT,
    sender_id TEXT,
    sender_name TEXT,
    content TEXT,
    role TEXT DEFAULT 'user',
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_message_logs_chat_id ON message_logs (chat_id);

CREATE TABLE IF NOT EXISTS archived_memories (
    id BIGSERIAL PRIMARY KEY,
    tag TEXT,
    summary TEXT NOT NULL,
    source_ids TEXT,
    source_count INTEGER DEFAULT 0,
    llm_model TEXT,
    confidence DOUBLE PRECISION,
    notes TEXT,
    compaction_level INTEGER DEFAULT 1,
    total_source_chars INTEGER DEFAULT 0,
    summary_chars INTEGER DEFAULT 0,
    created_by TEXT DEFAULT 'grillo_compactor',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_archived_memories_created_at ON archived_memories (created_at DESC);

CREATE TABLE IF NOT EXISTS llm_failure_log (
    id BIGSERIAL PRIMARY KEY,
    failure_code TEXT NOT NULL,
    stage TEXT NOT NULL,
    reason TEXT NOT NULL,
    interface_path TEXT,
    chat_id TEXT,
    thread_id TEXT,
    engine TEXT,
    model TEXT,
    message_id TEXT,
    content_preview TEXT,
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_failure_created_at ON llm_failure_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_failure_code ON llm_failure_log (failure_code);
CREATE INDEX IF NOT EXISTS idx_failure_stage ON llm_failure_log (stage);
CREATE INDEX IF NOT EXISTS idx_failure_interface_path ON llm_failure_log (interface_path);
CREATE INDEX IF NOT EXISTS idx_failure_engine ON llm_failure_log (engine);