services:

  synth:
    image: xargonwan/synthetic_heart:${IMAGE_VERSION:-latest-develop}
    container_name: synth
    hostname: synthetic-heart
    # Enable this if you're using a .env file for environment variables
    # Even in the services below
    # env_file:
    #   - .env
    ports:
      # Port used for the Synthetic Heart WebUI
      - "${SYNTH_WEBUI_HTTPS_PORT:-8000}:${SYNTH_WEBUI_HTTPS_PORT:-8000}"
      # Port used for Selkies (Web Desktop) HTTPS - This is shown via Login button for Selenium based LLMs
      - "${SELKIES_HTTPS_PORT:-3000}:3001"
      # Port used for Ollama integration.
      # NOTE: if you have an ollama server running locally, change this port to avoid conflicts.
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - synth_data:/config  # Persistent data storage
      - ./skins:/app/skins  # Custom skins, please download the skins from 
      - ./logs:/app/logs    # Application logs
    environment:
      # Timezone setting, if unset will be UTC and the Synth will think it's UTC
      - TZ=${TZ:-Asia/Tokyo}
      # This container don't need root access, so we set PUID and PGID to non-root user
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # Web Desktop root credentials
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      # Optional runtime variables (check wiki for details)
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - synth-db
    networks:
      - synth_network

  synth-db:
    container_name: synth-db
    hostname: synth-db
    image: mariadb:11
    # Enable this if you're using a .env file for environment variables
    # env_file:
    #   - .env
    ports:
      - "${EXT_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-synth}
      MYSQL_USER: ${DB_USER:-synth}
      MYSQL_PASSWORD: ${DB_PASS:-synth}
      MARIADB_AUTO_UPGRADE: 1
    command: --max-connections=200
    volumes:
      - synth_db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - synth_network

  synth-db-backup:
    container_name: synth-db-backup
    image: tiredofit/db-backup
    platform: ${PLATFORM_BACKUP:-linux/amd64}
    # Enable this if you're using a .env file for environment variables
    # env_file:
    #   - .env
    depends_on:
      - synth-db
    environment:
      DB_TYPE: mysql
      DB_HOST: ${DB_HOST:-synth-db}
      DB_NAME: ${DB_NAME:-synth}
      DB_USER: ${DB_USER:-synth}
      DB_PASS: ${DB_PASS:-synth}
      DB_DUMP_FREQ: 60
      DB_CLEANUP_TIME: 1440
      CONTAINER_TIMEZONE: ${TZ:-UTC}
      COMPRESSION: GZ
      DB_DUMP_TARGET: /backup
    volumes:
      - ./backups:/backup
    restart: unless-stopped
    networks:
      - synth_network

volumes:
  synth_db_data:
  synth_data:

networks:
  synth_network:
    driver: bridge
    name: synth_network


