"""
plugins/grillo/grillo_dream.py

Daily "dream" beat for G.R.I.L.L.O.: every day at configurable time (default 05:00 local)
collects recent chat fragments and memories and asks the LLM to generate a "dream".
The LLM is instructed to reply ONLY with valid JSON containing a single action:
{"actions": [{"type": "create_personal_diary_entry", "payload": {"content": "..."}}]}

The resulting diary entry is linked to the grillo_activity_log row for traceability.
"""

from __future__ import annotations

import asyncio
import random
from datetime import datetime, timedelta, time as dtime, timezone
from typing import List, Optional

from core.core_initializer import register_plugin
from core.logging_utils import log_info, log_debug, log_warning, log_error
from core.config_manager import config_registry
from core.time_zone_utils import get_local_timezone

# Local imports deferred to runtime to avoid cycles


class GrilloDreamPlugin:
    """Plugin that schedules a daily dream beat and enqueues it as a grillo message."""

    display_name = "G.R.I.L.L.O. Dream"

    _scheduler_running = False
    _scheduler_task: Optional[asyncio.Task] = None

    def __init__(self):
        # Configuration
        self.enabled = config_registry.get_value(
            "GRILLO_DREAM_ENABLED", True,
            label="Enable Grillo Dreams",
            description="Enable daily dreams generated by Grillo",
            value_type=bool,
            group="grillo",
            component="grillo_dream",
        )
        self.dream_time = config_registry.get_value(
            "GRILLO_DREAM_TIME", "05:00",
            label="Grillo Dream Time",
            description="Local time (HH:MM) when Grillo generates a dream each day",
            value_type=str,
            group="grillo",
            component="grillo_dream",
        )
        self.samples = int(config_registry.get_value(
            "GRILLO_DREAM_SAMPLES", 10,
            label="Grillo Dream Samples",
            description="Number of fragments to include in the dream prompt (mix of chat excerpts and memories)",
            value_type=int,
            group="grillo",
            component="grillo_dream",
        ))

        register_plugin("grillo_dream", self)
        log_info("[grillo_dream] Registered GrilloDreamPlugin")

        # Listen to config changes (best-effort)
        def _update_enabled(val):
            try:
                self.enabled = bool(val)
                log_info(f"[grillo_dream] enabled set to {self.enabled}")
            except Exception:
                pass
        config_registry.add_listener("GRILLO_DREAM_ENABLED", _update_enabled)

        def _update_time(val):
            try:
                self.dream_time = str(val or "05:00")
                log_info(f"[grillo_dream] dream_time set to {self.dream_time}")
            except Exception:
                pass
        config_registry.add_listener("GRILLO_DREAM_TIME", _update_time)

        def _update_samples(val):
            try:
                self.samples = int(val)
                log_info(f"[grillo_dream] samples set to {self.samples}")
            except Exception:
                pass
        config_registry.add_listener("GRILLO_DREAM_SAMPLES", _update_samples)

    def get_supported_action_types(self):
        return []

    def get_supported_actions(self):
        return {}

    async def start(self):
        if not self.enabled:
            log_info("[grillo_dream] Disabled by configuration; not starting scheduler")
            return

        if GrilloDreamPlugin._scheduler_task and not GrilloDreamPlugin._scheduler_task.done():
            log_debug("[grillo_dream] Scheduler already running")
            return

        GrilloDreamPlugin._scheduler_running = True
        GrilloDreamPlugin._scheduler_task = asyncio.create_task(self._dream_loop())
        log_info("[grillo_dream] Scheduler started")

    async def stop(self):
        GrilloDreamPlugin._scheduler_running = False
        task = GrilloDreamPlugin._scheduler_task
        if task and not task.done():
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
        GrilloDreamPlugin._scheduler_task = None
        log_info("[grillo_dream] Scheduler stopped")

    async def _dream_loop(self):
        log_info("[grillo_dream] Dream loop running")
        try:
            while GrilloDreamPlugin._scheduler_running:
                try:
                    # Compute seconds until next configured local time
                    wait_seconds = self._seconds_until_next_run(self.dream_time)
                    log_debug(f"[grillo_dream] Sleeping for {wait_seconds} seconds until next dream time {self.dream_time}")
                    # Sleep, but wake earlier if disabled
                    slept = 0
                    while slept < wait_seconds and GrilloDreamPlugin._scheduler_running:
                        to_sleep = min(60, wait_seconds - slept)
                        await asyncio.sleep(to_sleep)
                        slept += to_sleep
                    if not GrilloDreamPlugin._scheduler_running:
                        break

                    # On wake, perform the dream generation
                    await self._generate_dream()
                except asyncio.CancelledError:
                    break
                except Exception as e:
                    log_error(f"[grillo_dream] Error in dream loop: {e}")
                    await asyncio.sleep(60)
        finally:
            log_info("[grillo_dream] Dream loop exiting")

    def _seconds_until_next_run(self, hhmm: str) -> int:
        """Compute seconds until next occurrence of hh:mm in local timezone."""
        try:
            parts = hhmm.split(":")
            hour = int(parts[0])
            minute = int(parts[1]) if len(parts) > 1 else 0
        except Exception:
            hour, minute = 5, 0

        tz = get_local_timezone()
        now_local = datetime.now(tz)
        target_local = now_local.replace(hour=hour, minute=minute, second=0, microsecond=0)
        if target_local <= now_local:
            target_local = target_local + timedelta(days=1)

        # Convert to UTC and compute delta against UTC now
        target_utc = target_local.astimezone(timezone.utc)
        now_utc = datetime.utcnow().replace(tzinfo=timezone.utc)
        delta = (target_utc - now_utc).total_seconds()
        return max(0, int(delta))

    async def _generate_dream(self):
        """Collect fragments, build prompt, and enqueue dream for LLM processing."""
        try:
            if not self.enabled:
                log_info("[grillo_dream] Skipping dream generation because disabled")
                return

            fragments = await self._collect_fragments(self.samples)
            if not fragments:
                log_info("[grillo_dream] No fragments available to build dream; skipping")
                return

            prompt = self._build_dream_prompt(fragments)

            # Create activity log entry (linkable to diary later)
            try:
                from plugins.grillo.grillo_impl import GrilloPlugin
                activity_log_id = await GrilloPlugin.create_activity_log(beat_type="dream", prompt_text=prompt)
                # Definitive logging: include activity id and short prompt snippet for traceability
                try:
                    snippet = str(prompt).replace('\n', ' ')[:200]
                    log_info(f"[grillo_dream] Activity created: GRILLO_ACTIVITY id={activity_log_id} beat=dream samples={len(fragments)} prompt_snippet={snippet}")
                except Exception:
                    pass
            except Exception as e:
                log_debug(f"[grillo_dream] Could not create activity log: {e}")
                activity_log_id = None

            # Enqueue as low-priority grillo message (same pattern used by core/grillo)
            try:
                from types import SimpleNamespace
                from core import message_queue

                message = SimpleNamespace()
                message.chat_id = -1
                message.message_id = 0
                message.text = prompt
                message.from_user = SimpleNamespace(id=-1, username="grillo", full_name="G.R.I.L.L.O.", first_name="G.R.I.L.L.O.")
                message.chat = SimpleNamespace(id=-1, type="internal")
                message.date = datetime.utcnow()

                context = {
                    "grillo_beat": True,
                    "beat_type": "dream",
                    "activity_log_id": activity_log_id,
                    "grillo_fragments": fragments,
                }

                item = {
                    "bot": None,
                    "message": message,
                    "chat_id": message.chat_id,
                    "thread_id": None,
                    "interface": "grillo",
                    "chat_name": "G.R.I.L.L.O.",
                    "message_thread_name": None,
                    "timestamp": asyncio.get_event_loop().time(),
                    "context": context,
                    "priority": False,
                }

                await message_queue.enqueue_low_priority(None, message, context_memory=item.get('context'), interface_id='grillo', original_message=None)
                log_info("[grillo_dream] Dream enqueued for LLM processing")
            except Exception as e:
                log_error(f"[grillo_dream] Failed to enqueue dream: {e}")
        except Exception as e:
            log_error(f"[grillo_dream] Unexpected error in _generate_dream: {e}")

    async def _collect_fragments(self, limit: int) -> List[str]:
        """Collect text fragments from recent chats and memories. Returns truncated strings."""
        fragments: List[str] = []
        try:
            # 1) Recent chats
            try:
                import core.recent_chats as recent_chats
                from core.chat_history_cache import load_chat_history

                last = await recent_chats.get_last_active_chats_verbose(limit * 2)
                for chat_id, name in last:
                    if len(fragments) >= limit:
                        break
                    # Determine interface path
                    chat_path = recent_chats.get_chat_path(chat_id) or f"telegram_bot/{chat_id}"
                    try:
                        messages = await load_chat_history(chat_path)
                        # take up to 2 messages per chat (most recent)
                        taken = 0
                        for msg in reversed(list(messages)):
                            if not isinstance(msg, dict):
                                continue
                            text = msg.get('text')
                            sender = msg.get('sender_name') or msg.get('sender_id') or "unknown"
                            timestamp = msg.get('timestamp') or ""
                            if text:
                                snippet = text.strip()
                                if len(snippet) > 300:
                                    snippet = snippet[:300] + "..."
                                fragments.append(f"(chat:{chat_path} | sender:{sender} | {timestamp}) {snippet}")
                                taken += 1
                            if taken >= 2 or len(fragments) >= limit:
                                break
                    except Exception:
                        continue
            except Exception as e:
                log_debug(f"[grillo_dream] Failed to collect chat fragments: {e}")

            # 2) Random memories
            try:
                from core.db import get_conn_ctx
                async with get_conn_ctx() as conn:
                    async with conn.cursor() as cur:
                        await cur.execute("SELECT content FROM memories ORDER BY RAND() LIMIT %s", (limit,))
                        rows = await cur.fetchall()
                        for row in rows:
                            mem = row[0]
                            if not mem:
                                continue
                            mem_str = str(mem)
                            if len(mem_str) > 300:
                                mem_str = mem_str[:300] + "..."
                            fragments.append(f"(memory) {mem_str}")
            except Exception as e:
                log_debug(f"[grillo_dream] Failed to collect memories: {e}")

            # Shuffle and return up to limit unique fragments
            if fragments:
                random.shuffle(fragments)
                # deduplicate while preserving order
                seen = set()
                out = []
                for f in fragments:
                    if f in seen:
                        continue
                    seen.add(f)
                    out.append(f)
                    if len(out) >= limit:
                        break
                return out
            return []
        except Exception as e:
            log_error(f"[grillo_dream] Error collecting fragments: {e}")
            return []

    def _build_dream_prompt(self, fragments: List[str]) -> str:
        """Return a compact prompt instructing the LLM to "dream" and reply with JSON diary action."""
        header = "[G.R.I.L.L.O. DREAM] You are dreaming. Below are fragments from recent chats and memories. Create a single evocative dream narrative based on these fragments. Do NOT output any text outside a valid JSON object."

        # Include fragments as bullet list
        body = "\n\nFragments:\n"
        for i, f in enumerate(fragments, 1):
            body += f"{i}. {f}\n"

        from plugins.grillo.common_instructions import GRILLO_INSTRUCTIONS

        # Reuse shared GRILLO_INSTRUCTIONS and append dream-specific guidance
        instructions = (
            GRILLO_INSTRUCTIONS +
            "\n- Generate a single, cohesive dream narrative (approx 150-400 words).\n"
            "- RESPOND ONLY WITH VALID JSON following the exact format below (no prose outside JSON):\n"
            "{\"actions\": [{\"type\": \"create_personal_diary_entry\", \"payload\": {\"content\": \"...\"}}], \"meta\": {\"autonomous\": true, \"rationale\": \"Daily dream consolidation\"}}\n"
            "- The diary 'content' should be the generated dream text (plain text).\n"
            "- If you cannot generate a dream, reply with a JSON proposal explaining why (e.g., insufficient data)."
        )

        return header + body + instructions


PLUGIN_CLASS = GrilloDreamPlugin
