"""
core/action_safety.py

Centralized action safety checks used by `core.action_parser` to decide whether
an action generated by an LLM (or otherwise) may be executed automatically.

Rules implemented (first iteration):
- Each action can declare optional metadata: `security_level` (low|medium|high) and
  `external_effects` (list).
- Default `security_level` when missing is `low` (backwards compatible).
- If action has external effects declared, the effective level is bumped to at
  least `medium`.
- If action.payload has `safe=False` and `LLM_AUTO_EXECUTE_UNSAFE_ACTIONS` is False,
  the action is blocked.
- Decision depends on `SYNTH_AUTONOMY_MODE` (suggest|whitelisted|autonomous) and
  threshold config values `AUTONOMY_ALLOWED_SECURITY_LEVEL`, `GRILLO_ALLOWED_SECURITY_LEVEL`.

Return: (allowed: bool, reason: str, meta: dict)
"""

from __future__ import annotations

from typing import Tuple, Dict, Any
from core.logging_utils import log_debug, log_warning
from core.core_initializer import core_initializer
from core.config_manager import config_registry

LEVELS = ["low", "medium", "high"]


def register_action_safety_config() -> None:
    """Register the configuration keys used by action safety checks."""

    config_registry.get_var(
        "SYNTH_AUTONOMY_MODE",
        "suggest",
        value_type=str,
        label="Synth Autonomy Mode",
        description=(
            "Autonomy level: 'passive' (respond only), 'suggest' (propose actions), "
            "'whitelisted' (automatically execute only AUTONOMY_ALLOWED_ACTIONS), "
            "'autonomous' (execute actions up to AUTONOMY_ALLOWED_SECURITY_LEVEL)."
        ),
        constraints={"choices": ["passive", "suggest", "whitelisted", "autonomous"]},
        group="synth",
        component="persona",
    )
    config_registry.get_var(
        "AUTONOMY_ALLOWED_ACTIONS",
        [],
        value_type="json",
        label="Autonomy Allowed Actions",
        description=(
            "List of action types the synth may execute automatically when running in "
            "'whitelisted' mode."
        ),
        group="synth",
        component="persona",
    )
    config_registry.get_var(
        "AUTONOMY_ALLOWED_SECURITY_LEVEL",
        "high",
        value_type=str,
        label="Autonomy Allowed Security Level",
        description=(
            "Highest action security level the synth may auto-execute in 'autonomous' mode."
        ),
        constraints={"choices": LEVELS},
        group="synth",
        component="persona",
    )
    config_registry.get_var(
        "GRILLO_ALLOWED_ACTIONS",
        [],
        value_type="json",
        label="Grillo Allowed Actions",
        description=(
            "List of action types Grillo may execute regardless of the configured security threshold."
        ),
        group="grillo",
        component="grillo",
    )
    config_registry.get_var(
        "GRILLO_ALLOWED_SECURITY_LEVEL",
        "medium",
        value_type=str,
        label="Grillo Allowed Security Level",
        description="Highest action security level Grillo may auto-execute.",
        constraints={"choices": LEVELS},
        group="grillo",
        component="grillo",
    )
    config_registry.get_var(
        "LLM_AUTO_EXECUTE_UNSAFE_ACTIONS",
        False,
        value_type=bool,
        label="LLM auto-execute unsafe actions",
        description=(
            "Global override to allow execution of actions flagged safe=false when they originate from the LLM."
        ),
        group="synth",
        component="persona",
    )


register_action_safety_config()


def _coerce_level(level: str) -> str:
    if not level:
        return "low"
    lvl = str(level).lower()
    return lvl if lvl in LEVELS else "low"


def _level_at_least(level: str, minimum: str) -> str:
    try:
        if LEVELS.index(level) < LEVELS.index(minimum):
            return minimum
    except Exception:
        return minimum
    return level


def _get_declared_action_metadata(action_type: str) -> Dict[str, Any]:
    """Return declared metadata for an action type from core_initializer.actions_block"""
    try:
        actions = core_initializer.actions_block.get("available_actions", {})
        info = actions.get(action_type, {})
        return info
    except Exception as e:
        log_debug(
            f"[action_safety] Failed to get declared metadata for {action_type}: {e}"
        )
        return {}


def is_action_allowed_for_execution(
    action: Dict[str, Any], context: Dict[str, Any], original_message: Any
) -> Tuple[bool, str, Dict[str, Any]]:
    """Decide if the provided action can be executed automatically.

    Returns a tuple: (allowed, reason, metadata)
    """
    try:
        action_type = str(action.get("type") or "")

        # 1) Respect explicit safe flag
        safe_flag = action.get("safe", True)
        llm_unsafe_override = bool(
            config_registry.get_value("LLM_AUTO_EXECUTE_UNSAFE_ACTIONS", False)
        )
        if safe_flag is False and not llm_unsafe_override:
            return (
                False,
                "blocked: flagged unsafe and no global override",
                {"safe_flag": False},
            )

        # 2) Determine declared security level
        declared = _get_declared_action_metadata(action_type)
        declared_level = _coerce_level(
            str(declared.get("security_level") or declared.get("security") or "")
        )

        # 3) External effects bump
        ext = declared.get("external_effects") or []
        if ext:
            declared_level = _level_at_least(declared_level, "medium")

        # 4) Allow payload override if configured (human-origin actions only)
        """ allow_safe_override = bool(
            config_registry.get_value(
                "ALLOW_SAFE_FLAG_OVERRIDE",
                False,
                label="Allow Safe Flag Override",
                description=(
                    "Allow payload-level 'safe' overrides for human-origin actions. "
                    "Keep disabled unless you understand the security implications."
                ),
                value_type=bool,
                group="core",
                component="action_safety",
                advanced=True,
            )
        ) """

        # 5) Origin and mode
        is_from_cortex = (
            hasattr(original_message, "from_cortex")
            and getattr(original_message, "from_cortex")
        ) or (isinstance(context, dict) and context.get("from_cortex", False))
        synth_mode = str(
            config_registry.get_value("SYNTH_AUTONOMY_MODE", "suggest") or "suggest"
        ).lower()

        # Special-case: Grillo beats may have their own threshold
        is_grillo_beat = bool(context and context.get("grillo_beat"))
        if is_grillo_beat:
            grillo_level = _coerce_level(
                config_registry.get_value("GRILLO_ALLOWED_SECURITY_LEVEL", "medium")
                or "medium"
            )
            # Also allow explicit per-action whitelist for grillo
            grillo_allowed_actions = (
                config_registry.get_value("GRILLO_ALLOWED_ACTIONS", []) or []
            )
            if action_type in grillo_allowed_actions:
                return (
                    True,
                    "allowed: explicitly whitelisted for grillo",
                    {"security_level": declared_level},
                )
            if LEVELS.index(declared_level) <= LEVELS.index(grillo_level):
                return (
                    True,
                    f"allowed: grillo threshold {grillo_level} >= {declared_level}",
                    {"security_level": declared_level},
                )
            return (
                False,
                f"blocked: grillo threshold {grillo_level} lower than action {declared_level}",
                {"security_level": declared_level},
            )

        # If not from LLM (human-triggered), allow (unless payload safe flag blocks and override not set)
        if not is_from_cortex:
            return True, "allowed: human-triggered", {"security_level": declared_level}

        # From LLM -> apply synth_mode policies
        if synth_mode == "whitelisted":
            allowed_autonomy = (
                config_registry.get_value("AUTONOMY_ALLOWED_ACTIONS", []) or []
            )
            if action_type in allowed_autonomy:
                return (
                    True,
                    "allowed: whitelisted action",
                    {"security_level": declared_level},
                )
            return False, "blocked: not whitelisted", {"security_level": declared_level}

        # Low-security LLM actions remain auto-executable outside explicit whitelist mode.
        if declared_level == "low":
            return (
                True,
                "allowed: declared low security",
                {"security_level": "low", "declared": declared},
            )

        if synth_mode == "suggest":
            # Proposal-only for anything above low (low already returned earlier)
            return (
                False,
                "blocked: synth in 'suggest' mode, proposals only for non-low actions",
                {"security_level": declared_level},
            )

        if synth_mode == "autonomous":
            # Check configured allowed level (default high)
            allowed_level = _coerce_level(
                config_registry.get_value("AUTONOMY_ALLOWED_SECURITY_LEVEL", "high")
                or "high"
            )
            if LEVELS.index(declared_level) <= LEVELS.index(allowed_level):
                return (
                    True,
                    "allowed: autonomous mode threshold satisfied",
                    {"security_level": declared_level},
                )
            return (
                False,
                "blocked: autonomous threshold lower than action",
                {"security_level": declared_level},
            )

        # Fallback conservative: block
        return (
            False,
            "blocked: unknown mode or policy",
            {"security_level": declared_level},
        )

    except Exception as e:
        log_warning(
            f"[action_safety] Decision failed for action {action.get('type')}: {e}"
        )
        return False, "blocked: safety decision error", {"error": str(e)}
