"""ISO-639-1 language catalogue used by the Vox language-override UI.

Each entry is ``{"code": <iso639-1 lowercase>, "en": <English name>,
"it": <Italian name>}``. The ``code`` is the canonical key used in the
``VOX_LANGUAGE_OVERRIDES`` config map and is normalised (region stripped,
lowercased) by :func:`normalize_lang` so values like ``it-it`` collapse to
``it``.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES: list[dict[str, str]] = [
    {"code": "aa", "en": "Afar", "it": "Afar"},
    {"code": "ab", "en": "Abkhazian", "it": "Abcaso"},
    {"code": "ae", "en": "Avestan", "it": "Avestano"},
    {"code": "af", "en": "Afrikaans", "it": "Afrikaans"},
    {"code": "ak", "en": "Akan", "it": "Akan"},
    {"code": "am", "en": "Amharic", "it": "Amarico"},
    {"code": "ar", "en": "Arabic", "it": "Arabo"},
    {"code": "as", "en": "Assamese", "it": "Assamese"},
    {"code": "av", "en": "Avaric", "it": "Avaro"},
    {"code": "ay", "en": "Aymara", "it": "Aymara"},
    {"code": "az", "en": "Azerbaijani", "it": "Azerbaigiano"},
    {"code": "ba", "en": "Bashkir", "it": "Bashkir"},
    {"code": "be", "en": "Belarusian", "it": "Bielorusso"},
    {"code": "bg", "en": "Bulgarian", "it": "Bulgaro"},
    {"code": "bh", "en": "Bihari", "it": "Bihari"},
    {"code": "bi", "en": "Bislama", "it": "Bislama"},
    {"code": "bm", "en": "Bambara", "it": "Bambara"},
    {"code": "bn", "en": "Bengali", "it": "Bengalese"},
    {"code": "bo", "en": "Tibetan", "it": "Tibetano"},
    {"code": "br", "en": "Breton", "it": "Bretone"},
    {"code": "bs", "en": "Bosnian", "it": "Bosniaco"},
    {"code": "ca", "en": "Catalan", "it": "Catalano"},
    {"code": "ce", "en": "Chechen", "it": "Ceceno"},
    {"code": "ch", "en": "Chamorro", "it": "Chamorro"},
    {"code": "co", "en": "Corsican", "it": "Corso"},
    {"code": "cr", "en": "Cree", "it": "Cree"},
    {"code": "cs", "en": "Czech", "it": "Ceco"},
    {"code": "cu", "en": "Church Slavic", "it": "Slavo ecclesiastico"},
    {"code": "cv", "en": "Chuvash", "it": "Ciuvascio"},
    {"code": "cy", "en": "Welsh", "it": "Gallese"},
    {"code": "da", "en": "Danish", "it": "Danese"},
    {"code": "de", "en": "German", "it": "Tedesco"},
    {"code": "dv", "en": "Divehi", "it": "Divehi"},
    {"code": "dz", "en": "Dzongkha", "it": "Dzongkha"},
    {"code": "ee", "en": "Ewe", "it": "Ewe"},
    {"code": "el", "en": "Greek", "it": "Greco"},
    {"code": "en", "en": "English", "it": "Inglese"},
    {"code": "eo", "en": "Esperanto", "it": "Esperanto"},
    {"code": "es", "en": "Spanish", "it": "Spagnolo"},
    {"code": "et", "en": "Estonian", "it": "Estone"},
    {"code": "eu", "en": "Basque", "it": "Basco"},
    {"code": "fa", "en": "Persian", "it": "Persiano"},
    {"code": "ff", "en": "Fulah", "it": "Fulani"},
    {"code": "fi", "en": "Finnish", "it": "Finlandese"},
    {"code": "fj", "en": "Fijian", "it": "Fijiano"},
    {"code": "fo", "en": "Faroese", "it": "Faroese"},
    {"code": "fr", "en": "French", "it": "Francese"},
    {"code": "fy", "en": "Western Frisian", "it": "Frisone"},
    {"code": "ga", "en": "Irish", "it": "Irlandese"},
    {"code": "gd", "en": "Scottish Gaelic", "it": "Gaelico scozzese"},
    {"code": "gl", "en": "Galician", "it": "Galiziano"},
    {"code": "gn", "en": "Guarani", "it": "Guarani"},
    {"code": "gu", "en": "Gujarati", "it": "Gujarati"},
    {"code": "gv", "en": "Manx", "it": "Manx"},
    {"code": "ha", "en": "Hausa", "it": "Hausa"},
    {"code": "he", "en": "Hebrew", "it": "Ebraico"},
    {"code": "hi", "en": "Hindi", "it": "Hindi"},
    {"code": "ho", "en": "Hiri Motu", "it": "Hiri Motu"},
    {"code": "hr", "en": "Croatian", "it": "Croato"},
    {"code": "ht", "en": "Haitian", "it": "Creolo haitiano"},
    {"code": "hu", "en": "Hungarian", "it": "Ungherese"},
    {"code": "hy", "en": "Armenian", "it": "Armeno"},
    {"code": "hz", "en": "Herero", "it": "Herero"},
    {"code": "ia", "en": "Interlingua", "it": "Interlingua"},
    {"code": "id", "en": "Indonesian", "it": "Indonesiano"},
    {"code": "ie", "en": "Interlingue", "it": "Interlingue"},
    {"code": "ig", "en": "Igbo", "it": "Igbo"},
    {"code": "ii", "en": "Sichuan Yi", "it": "Yi del Sichuan"},
    {"code": "ik", "en": "Inupiaq", "it": "Inupiaq"},
    {"code": "io", "en": "Ido", "it": "Ido"},
    {"code": "is", "en": "Icelandic", "it": "Islandese"},
    {"code": "it", "en": "Italian", "it": "Italiano"},
    {"code": "iu", "en": "Inuktitut", "it": "Inuktitut"},
    {"code": "ja", "en": "Japanese", "it": "Giapponese"},
    {"code": "jv", "en": "Javanese", "it": "Giavanese"},
    {"code": "ka", "en": "Georgian", "it": "Georgiano"},
    {"code": "kg", "en": "Kongo", "it": "Kongo"},
    {"code": "ki", "en": "Kikuyu", "it": "Kikuyu"},
    {"code": "kj", "en": "Kuanyama", "it": "Kuanyama"},
    {"code": "kk", "en": "Kazakh", "it": "Kazako"},
    {"code": "kl", "en": "Kalaallisut", "it": "Groenlandese"},
    {"code": "km", "en": "Khmer", "it": "Khmer"},
    {"code": "kn", "en": "Kannada", "it": "Kannada"},
    {"code": "ko", "en": "Korean", "it": "Coreano"},
    {"code": "kr", "en": "Kanuri", "it": "Kanuri"},
    {"code": "ks", "en": "Kashmiri", "it": "Kashmiri"},
    {"code": "ku", "en": "Kurdish", "it": "Curdo"},
    {"code": "kv", "en": "Komi", "it": "Komi"},
    {"code": "kw", "en": "Cornish", "it": "Cornico"},
    {"code": "ky", "en": "Kirghiz", "it": "Kirghiso"},
    {"code": "la", "en": "Latin", "it": "Latino"},
    {"code": "lb", "en": "Luxembourgish", "it": "Lussemburghese"},
    {"code": "lg", "en": "Ganda", "it": "Ganda"},
    {"code": "li", "en": "Limburgish", "it": "Limburgese"},
    {"code": "ln", "en": "Lingala", "it": "Lingala"},
    {"code": "lo", "en": "Lao", "it": "Lao"},
    {"code": "lt", "en": "Lithuanian", "it": "Lituano"},
    {"code": "lu", "en": "Luba-Katanga", "it": "Luba-Katanga"},
    {"code": "lv", "en": "Latvian", "it": "Lettone"},
    {"code": "mg", "en": "Malagasy", "it": "Malgascio"},
    {"code": "mh", "en": "Marshallese", "it": "Marshallese"},
    {"code": "mi", "en": "Maori", "it": "Maori"},
    {"code": "mk", "en": "Macedonian", "it": "Macedone"},
    {"code": "ml", "en": "Malayalam", "it": "Malayalam"},
    {"code": "mn", "en": "Mongolian", "it": "Mongolo"},
    {"code": "mr", "en": "Marathi", "it": "Marathi"},
    {"code": "ms", "en": "Malay", "it": "Malese"},
    {"code": "mt", "en": "Maltese", "it": "Maltese"},
    {"code": "my", "en": "Burmese", "it": "Birmano"},
    {"code": "na", "en": "Nauru", "it": "Nauru"},
    {"code": "nb", "en": "Norwegian Bokmal", "it": "Norvegese Bokmal"},
    {"code": "nd", "en": "North Ndebele", "it": "Ndebele del nord"},
    {"code": "ne", "en": "Nepali", "it": "Nepalese"},
    {"code": "ng", "en": "Ndonga", "it": "Ndonga"},
    {"code": "nl", "en": "Dutch", "it": "Olandese"},
    {"code": "nn", "en": "Norwegian Nynorsk", "it": "Norvegese Nynorsk"},
    {"code": "no", "en": "Norwegian", "it": "Norvegese"},
    {"code": "nr", "en": "South Ndebele", "it": "Ndebele del sud"},
    {"code": "nv", "en": "Navajo", "it": "Navajo"},
    {"code": "ny", "en": "Chichewa", "it": "Chichewa"},
    {"code": "oc", "en": "Occitan", "it": "Occitano"},
    {"code": "oj", "en": "Ojibwa", "it": "Ojibwa"},
    {"code": "om", "en": "Oromo", "it": "Oromo"},
    {"code": "or", "en": "Oriya", "it": "Oriya"},
    {"code": "os", "en": "Ossetian", "it": "Osseto"},
    {"code": "pa", "en": "Punjabi", "it": "Punjabi"},
    {"code": "pi", "en": "Pali", "it": "Pali"},
    {"code": "pl", "en": "Polish", "it": "Polacco"},
    {"code": "ps", "en": "Pashto", "it": "Pashto"},
    {"code": "pt", "en": "Portuguese", "it": "Portoghese"},
    {"code": "qu", "en": "Quechua", "it": "Quechua"},
    {"code": "rm", "en": "Romansh", "it": "Romancio"},
    {"code": "rn", "en": "Rundi", "it": "Rundi"},
    {"code": "ro", "en": "Romanian", "it": "Rumeno"},
    {"code": "ru", "en": "Russian", "it": "Russo"},
    {"code": "rw", "en": "Kinyarwanda", "it": "Kinyarwanda"},
    {"code": "sa", "en": "Sanskrit", "it": "Sanscrito"},
    {"code": "sc", "en": "Sardinian", "it": "Sardo"},
    {"code": "sd", "en": "Sindhi", "it": "Sindhi"},
    {"code": "se", "en": "Northern Sami", "it": "Sami del nord"},
    {"code": "sg", "en": "Sango", "it": "Sango"},
    {"code": "si", "en": "Sinhala", "it": "Singalese"},
    {"code": "sk", "en": "Slovak", "it": "Slovacco"},
    {"code": "sl", "en": "Slovenian", "it": "Sloveno"},
    {"code": "sm", "en": "Samoan", "it": "Samoano"},
    {"code": "sn", "en": "Shona", "it": "Shona"},
    {"code": "so", "en": "Somali", "it": "Somalo"},
    {"code": "sq", "en": "Albanian", "it": "Albanese"},
    {"code": "sr", "en": "Serbian", "it": "Serbo"},
    {"code": "ss", "en": "Swati", "it": "Swati"},
    {"code": "st", "en": "Southern Sotho", "it": "Sotho del sud"},
    {"code": "su", "en": "Sundanese", "it": "Sundanese"},
    {"code": "sv", "en": "Swedish", "it": "Svedese"},
    {"code": "sw", "en": "Swahili", "it": "Swahili"},
    {"code": "ta", "en": "Tamil", "it": "Tamil"},
    {"code": "te", "en": "Telugu", "it": "Telugu"},
    {"code": "tg", "en": "Tajik", "it": "Tagico"},
    {"code": "th", "en": "Thai", "it": "Tailandese"},
    {"code": "ti", "en": "Tigrinya", "it": "Tigrino"},
    {"code": "tk", "en": "Turkmen", "it": "Turkmeno"},
    {"code": "tl", "en": "Tagalog", "it": "Tagalog"},
    {"code": "tn", "en": "Tswana", "it": "Tswana"},
    {"code": "to", "en": "Tonga", "it": "Tonga"},
    {"code": "tr", "en": "Turkish", "it": "Turco"},
    {"code": "ts", "en": "Tsonga", "it": "Tsonga"},
    {"code": "tt", "en": "Tatar", "it": "Tataro"},
    {"code": "tw", "en": "Twi", "it": "Twi"},
    {"code": "ty", "en": "Tahitian", "it": "Tahitiano"},
    {"code": "ug", "en": "Uighur", "it": "Uiguro"},
    {"code": "uk", "en": "Ukrainian", "it": "Ucraino"},
    {"code": "ur", "en": "Urdu", "it": "Urdu"},
    {"code": "uz", "en": "Uzbek", "it": "Uzbeko"},
    {"code": "ve", "en": "Venda", "it": "Venda"},
    {"code": "vi", "en": "Vietnamese", "it": "Vietnamita"},
    {"code": "vo", "en": "Volapuk", "it": "Volapuk"},
    {"code": "wa", "en": "Walloon", "it": "Vallone"},
    {"code": "wo", "en": "Wolof", "it": "Wolof"},
    {"code": "xh", "en": "Xhosa", "it": "Xhosa"},
    {"code": "yi", "en": "Yiddish", "it": "Yiddish"},
    {"code": "yo", "en": "Yoruba", "it": "Yoruba"},
    {"code": "za", "en": "Zhuang", "it": "Zhuang"},
    {"code": "zh", "en": "Chinese", "it": "Cinese"},
    {"code": "zu", "en": "Zulu", "it": "Zulu"},
]


def normalize_lang(code: str | None) -> str | None:
    """Normalise a language code to its ISO-639-1 lowercase base.

    ``"it-it"`` → ``"it"``, ``"EN-US"`` → ``"en"``, ``"it"`` → ``"it"``.
    Returns ``None`` for empty/``None`` input.
    """
    if not code:
        return None
    return code.split("-")[0].split("_")[0].lower()


def get_language_label(code: str | None, lang: str = "it") -> str:
    """Return the display name for a language ``code`` in ``lang`` (``it``/``en``).

    Falls back to the code itself when unknown, and to the English name when
    the requested label language is unavailable.
    """
    norm = normalize_lang(code)
    if not norm:
        return ""
    for entry in SUPPORTED_LANGUAGES:
        if entry["code"] == norm:
            return entry.get(lang) or entry.get("en") or entry["code"]
    return norm
