"""
plugins/grillo/grillo_dream/grillo_dream.py

Daily "dream" beat for G.R.I.L.L.O.: every day at configurable time (default 05:00 local)
collects recent chat fragments and memories and asks the LLM to generate a "dream".
The LLM is instructed to reply ONLY with valid JSON containing a single action:
{"actions": [{"type": "create_personal_diary_entry", "payload": {"content": "..."}}]}

The resulting diary entry is linked to the grillo_activity_log row for traceability.
"""

from __future__ import annotations

import asyncio
import random
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from core.core_initializer import register_plugin
from core.logging_utils import log_info, log_debug, log_error
from core.config_manager import config_registry
from core.time_zone_utils import get_local_timezone

# Local imports deferred to runtime to avoid cycles


class GrilloDreamPlugin:
    """Plugin that schedules a daily dream beat and enqueues it as a grillo message."""

    display_name = "G.R.I.L.L.O. Dream"

    _scheduler_running = False
    _scheduler_task: Optional[asyncio.Task] = None

    def __init__(self):
        # Configuration
        self.enabled = config_registry.get_value(
            "GRILLO_DREAM_ENABLED",
            True,
            label="Enable Grillo Dreams",
            description="Enable daily dreams generated by Grillo",
            value_type=bool,
            group="grillo",
            component="grillo_dream",
            hidden=True,
        )
        self.dream_time = config_registry.get_value(
            "GRILLO_DREAM_TIME",
            "05:00",
            label="Grillo Dream Time",
            description="Local time (HH:MM) when Grillo generates a dream each day",
            value_type=str,
            group="grillo",
            component="grillo_dream",
        )
        self.samples = int(
            config_registry.get_value(
                "GRILLO_DREAM_SAMPLES",
                10,
                label="Grillo Dream Samples",
                description="Number of fragments to include in the dream prompt (mix of chat excerpts and memories)",
                value_type=int,
                group="grillo",
                component="grillo_dream",
            )
        )
        self.inject_until = config_registry.get_value(
            "GRILLO_DREAM_INJECT_UNTIL",
            "12:00",
            label="Grillo Dream Inject Until",
            description="Local time (HH:MM) until which today's dream is injected into prompts. After this time the dream is no longer injected.",
            value_type=str,
            group="grillo",
            component="grillo_dream",
        )
        # Recon gate: when disabled the last-dream recall is not offered to the
        # combined Recon LLM call. Key name must match the Recon convention
        # (_plugin_key(plugin) + "_RECON_ENABLED") so core.recon can honour it.
        config_registry.get_value(
            "GRILLO_DREAM_RECON_ENABLED",
            True,
            label="Enable Grillo Dream Recall (Recon)",
            description="Allow the persona to recall its most recent dream via Recon when the human asks about it.",
            value_type=bool,
            group="grillo",
            component="grillo_dream",
        )

        register_plugin("grillo_dream", self)
        log_info("[grillo_dream] Registered GrilloDreamPlugin")

        # Listen to config changes (best-effort)
        def _update_enabled(val):
            try:
                self.enabled = bool(val)
                log_info(f"[grillo_dream] enabled set to {self.enabled}")
            except Exception:
                pass

        config_registry.add_listener("GRILLO_DREAM_ENABLED", _update_enabled)

        def _update_time(val):
            try:
                self.dream_time = str(val or "05:00")
                log_info(f"[grillo_dream] dream_time set to {self.dream_time}")
            except Exception:
                pass

        config_registry.add_listener("GRILLO_DREAM_TIME", _update_time)

        def _update_samples(val):
            try:
                self.samples = int(val)
                log_info(f"[grillo_dream] samples set to {self.samples}")
            except Exception:
                pass

        config_registry.add_listener("GRILLO_DREAM_SAMPLES", _update_samples)

        def _update_inject_until(val):
            try:
                self.inject_until = str(val or "12:00")
                log_info(f"[grillo_dream] inject_until set to {self.inject_until}")
            except Exception:
                pass

        config_registry.add_listener("GRILLO_DREAM_INJECT_UNTIL", _update_inject_until)

    def get_supported_action_types(self):
        return ["static_inject"]

    def get_supported_actions(self):
        return {}

    # ------------------------------------------------------------------
    # Recon: recall the most recent dream on demand
    # ------------------------------------------------------------------
    # ``recall_last_dream`` used to be a standalone action. It is now a Recon
    # contribution: the combined Recon LLM call decides whether the user is
    # asking to hear about the last dream, and if so this plugin fetches the
    # most recent dream from ``grillo_activity_log`` and contributes its text.
    recon_priority = 7

    def get_recon_key(self) -> str:
        return "recall_last_dream"

    def get_recon_instruction(self) -> str:
        return (
            "Set to true ONLY if the human is explicitly asking to hear about, "
            "recall, or be reminded of the persona's most recent dream. "
            'Return an object: {"wants_dream": true} or {"wants_dream": false}.'
        )

    async def parse_recon_response(
        self,
        data,
        *,
        message=None,
        context_memory=None,
        text: str | None = None,
        tags: List[str] | None = None,
        keywords: List[str] | None = None,
        max_results: int = 5,
        _raw_llm_text: str | None = None,
    ) -> list[dict]:
        """Contribute the last dream's text when the Recon call flags a request."""
        wants_dream = False
        if isinstance(data, dict):
            wants_dream = bool(data.get("wants_dream"))
        elif isinstance(data, bool):
            wants_dream = data

        if not wants_dream:
            return []

        dream_text, executed_at = await self._fetch_last_dream()
        if not dream_text:
            return []

        return [
            {
                "type": "snippet",
                "content": (
                    "=== Recalled Dream ===\n"
                    "The human asked about your most recent dream. Recount it "
                    "naturally, in your own words.\n\n"
                    f"{dream_text}"
                ),
                "source": "grillo_dream",
                "priority": int(self.recon_priority),
                "id": executed_at.isoformat() if executed_at else "last_dream",
            }
        ]

    async def _fetch_last_dream(self):
        """Return ``(dream_text, executed_at)`` for the most recent dream beat.

        Returns ``(None, None)`` when no dream is on record or the content
        cannot be recovered.
        """
        try:
            from core.db import get_conn_ctx

            async with get_conn_ctx() as conn:
                async with conn.cursor() as cur:
                    await cur.execute(
                        """
                        SELECT g.response_text, d.content, g.executed_at
                        FROM grillo_activity_log g
                        LEFT JOIN ai_diary d ON g.diary_entry_id = d.id
                        WHERE g.beat_type = 'dream'
                        ORDER BY g.id DESC
                        LIMIT 1
                        """
                    )
                    row = await cur.fetchone()

            if not row:
                return None, None

            response_text, diary_content, executed_at = row
            # The dream text lives inside response_text (JSON action payload);
            # the linked diary entry is an unrelated interaction diary, so it is
            # only a last-resort fallback.
            dream_text = self._extract_dream_text(response_text) or diary_content
            return (dream_text or None), executed_at
        except Exception as e:
            log_error(f"[grillo_dream] Failed to fetch last dream: {e}")
            return None, None

    @staticmethod
    def _extract_dream_text(response_text) -> Optional[str]:
        """Extract the readable dream text from a dream beat's ``response_text``.

        Dream beats store the LLM output as a JSON action envelope
        (``{"actions": [{"type": ..., "payload": {"content": "..."}}]}``). The
        readable dream is the first action payload ``content``.
        """
        if not response_text or not isinstance(response_text, str):
            return None
        import json as _json

        try:
            data = _json.loads(response_text)
        except (ValueError, TypeError):
            return None
        if not isinstance(data, dict):
            return None
        actions = data.get("actions")
        if not isinstance(actions, list):
            return None
        for action in actions:
            if not isinstance(action, dict):
                continue
            payload = action.get("payload")
            if isinstance(payload, dict):
                content = payload.get("content")
                if isinstance(content, str) and content.strip():
                    return content.strip()
        return None

    async def _fetch_todays_dream(self) -> Optional[str]:
        """Return the content of today's dream, or None if none was generated today."""
        try:
            from core.db import get_conn_ctx

            tz = get_local_timezone()
            today = datetime.now(tz).date()

            async with get_conn_ctx() as conn:
                async with conn.cursor() as cur:
                    await cur.execute(
                        """
                        SELECT g.response_text, d.content, g.executed_at
                        FROM grillo_activity_log g
                        LEFT JOIN ai_diary d ON g.diary_entry_id = d.id
                        WHERE g.beat_type = 'dream'
                        ORDER BY g.id DESC
                        LIMIT 1
                        """
                    )
                    row = await cur.fetchone()

            if not row:
                return None

            response_text, diary_content, executed_at = row
            if executed_at is None:
                return None

            # Normalise the executed_at timestamp to a local date for comparison.
            if executed_at.tzinfo is None:
                executed_at = executed_at.replace(tzinfo=timezone.utc)
            executed_date = executed_at.astimezone(tz).date()
            if executed_date != today:
                return None

            # The readable dream lives inside response_text (JSON action
            # payload); the linked diary entry is unrelated, so it is only a
            # last-resort fallback.
            content = self._extract_dream_text(response_text) or diary_content
            return content or None
        except Exception as e:
            log_error(f"[grillo_dream] Failed to fetch today's dream: {e}")
            return None

    def _within_injection_window(self) -> bool:
        """True if the current local time is before the configured cutoff time."""
        try:
            cutoff_raw = str(self.inject_until or "12:00").strip()
            hour_str, _, minute_str = cutoff_raw.partition(":")
            cutoff_hour = int(hour_str)
            cutoff_minute = int(minute_str) if minute_str else 0
        except Exception:
            cutoff_hour, cutoff_minute = 12, 0

        now = datetime.now(get_local_timezone())
        cutoff_minutes = cutoff_hour * 60 + cutoff_minute
        now_minutes = now.hour * 60 + now.minute
        return now_minutes < cutoff_minutes

    async def get_static_injection(self, message=None, context_memory=None) -> dict:
        """Inject today's dream into the prompt until the configured cutoff time.

        Mirrors the diary static-injection contract. Returns an empty dict when
        the plugin is disabled, no dream exists for today, or the current local
        time is past ``GRILLO_DREAM_INJECT_UNTIL``.
        """
        if not self.enabled:
            return {}

        if not self._within_injection_window():
            return {}

        dream = await self._fetch_todays_dream()
        if not dream:
            return {}

        return {
            "todays_dream": (
                "=== Today's Dream ===\n"
                "You had the following dream last night. Let it gently colour your "
                "mood and thoughts today; you may reference it naturally if relevant, "
                "but do not recite it verbatim unless asked.\n\n"
                f"{dream}"
            )
        }

    async def start(self):
        if not self.enabled:
            log_info("[grillo_dream] Disabled by configuration; not starting scheduler")
            return

        if (
            GrilloDreamPlugin._scheduler_task
            and not GrilloDreamPlugin._scheduler_task.done()
        ):
            log_debug("[grillo_dream] Scheduler already running")
            return

        GrilloDreamPlugin._scheduler_running = True
        GrilloDreamPlugin._scheduler_task = asyncio.create_task(self._dream_loop())
        log_info("[grillo_dream] Scheduler started")

    async def stop(self):
        GrilloDreamPlugin._scheduler_running = False
        task = GrilloDreamPlugin._scheduler_task
        if task and not task.done():
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
        GrilloDreamPlugin._scheduler_task = None
        log_info("[grillo_dream] Scheduler stopped")

    async def _dream_loop(self):
        log_info("[grillo_dream] Dream loop running")
        try:
            while GrilloDreamPlugin._scheduler_running:
                try:
                    # Compute seconds until next configured local time
                    wait_seconds = self._seconds_until_next_run(self.dream_time)
                    log_debug(
                        f"[grillo_dream] Sleeping for {wait_seconds} seconds until next dream time {self.dream_time}"
                    )
                    # Sleep, but wake earlier if disabled
                    slept = 0
                    while slept < wait_seconds and GrilloDreamPlugin._scheduler_running:
                        to_sleep = min(60, wait_seconds - slept)
                        await asyncio.sleep(to_sleep)
                        slept += to_sleep
                    if not GrilloDreamPlugin._scheduler_running:
                        break

                    # On wake, perform the dream generation
                    await self._generate_dream()
                except asyncio.CancelledError:
                    break
                except Exception as e:
                    log_error(f"[grillo_dream] Error in dream loop: {e}")
                    await asyncio.sleep(60)
        finally:
            log_info("[grillo_dream] Dream loop exiting")

    def _seconds_until_next_run(self, hhmm: str) -> int:
        """Compute seconds until next occurrence of hh:mm in local timezone."""
        try:
            parts = hhmm.split(":")
            hour = int(parts[0])
            minute = int(parts[1]) if len(parts) > 1 else 0
        except Exception:
            hour, minute = 5, 0

        tz = get_local_timezone()
        now_local = datetime.now(tz)
        target_local = now_local.replace(
            hour=hour, minute=minute, second=0, microsecond=0
        )
        if target_local <= now_local:
            target_local = target_local + timedelta(days=1)

        # Convert to UTC and compute delta against UTC now
        target_utc = target_local.astimezone(timezone.utc)
        now_utc = datetime.utcnow().replace(tzinfo=timezone.utc)
        delta = (target_utc - now_utc).total_seconds()
        return max(0, int(delta))

    async def _generate_dream(self):
        """Collect fragments, build prompt, and enqueue dream for LLM processing."""
        try:
            if not self.enabled:
                log_info("[grillo_dream] Skipping dream generation because disabled")
                return

            fragments = await self._collect_fragments(self.samples)
            if not fragments:
                log_info(
                    "[grillo_dream] No fragments available to build dream; skipping"
                )
                return

            prompt = self._build_dream_prompt(fragments)

            # Create activity log entry (linkable to diary later)
            try:
                from plugins.grillo.grillo_impl import GrilloPlugin

                activity_log_id = await GrilloPlugin.create_activity_log(
                    beat_type="dream", prompt_text=prompt
                )
                # Definitive logging: include activity id and short prompt snippet for traceability
                try:
                    snippet = str(prompt).replace("\n", " ")[:200]
                    log_info(
                        f"[grillo_dream] Activity created: GRILLO_ACTIVITY id={activity_log_id} beat=dream samples={len(fragments)} prompt_snippet={snippet}"
                    )
                except Exception:
                    pass
            except Exception as e:
                log_debug(f"[grillo_dream] Could not create activity log: {e}")
                activity_log_id = None

            # Enqueue as low-priority grillo message (same pattern used by core/grillo)
            try:
                from types import SimpleNamespace
                from core import message_queue

                message = SimpleNamespace()
                message.chat_id = -1
                message.message_id = 0
                message.text = prompt
                message.from_user = SimpleNamespace(
                    id=-1,
                    username="grillo",
                    full_name="G.R.I.L.L.O.",
                    first_name="G.R.I.L.L.O.",
                )
                message.chat = SimpleNamespace(id=-1, type="internal")
                message.date = datetime.utcnow()

                context = {
                    "grillo_beat": True,
                    "beat_type": "dream",
                    "activity_log_id": activity_log_id,
                    "grillo_fragments": fragments,
                }

                item = {
                    "bot": None,
                    "message": message,
                    "chat_id": message.chat_id,
                    "thread_id": None,
                    "interface": "grillo",
                    "chat_name": "G.R.I.L.L.O.",
                    "message_thread_name": None,
                    "timestamp": asyncio.get_event_loop().time(),
                    "context": context,
                    "priority": False,
                }

                await message_queue.enqueue_low_priority(
                    None,
                    message,
                    context_memory=item.get("context"),
                    interface_id="grillo",
                    original_message=None,
                )
                log_info("[grillo_dream] Dream enqueued for LLM processing")
            except Exception as e:
                log_error(f"[grillo_dream] Failed to enqueue dream: {e}")
        except Exception as e:
            log_error(f"[grillo_dream] Unexpected error in _generate_dream: {e}")

    def _is_dream_relevant(self, text: str, sender: str = "") -> bool:
        """Filter out non-dream-relevant content (weather, system messages, etc.)."""
        if not text:
            return False

        # Ignore system bots
        system_senders = ["System", "WeatherBot", "Scheduler", "Announcer"]
        if sender and sender in system_senders:
            return False

        # Ignore common weather/system patterns
        # We use specific phrases to avoid blocking valid user queries about weather
        blocklist = [
            "Current weather:",
            "Weather report",
            "Temperature:",
            "Forecast:",
            "Humidity:",
            "Wind:",
            "degrees Celsius",
            "°C",
            "System online",
            "I have completed the analysis",
            "Action schema",
            "[System Message]",
            "Analysis of recent memory",
            "I have successfully processed",
        ]

        text_lower = text.lower()
        for phrase in blocklist:
            if phrase.lower() in text_lower:
                return False

        # Ignore raw JSON/System outputs (starts and ends with braces/brackets)
        stripped = text.strip()
        if (stripped.startswith("{") and stripped.endswith("}")) or (
            stripped.startswith("[") and stripped.endswith("]")
        ):
            return False

        return True

    async def _collect_fragments(self, limit: int) -> List[str]:
        """Collect text fragments from recent chats and memories. Returns truncated strings."""
        fragments: List[str] = []
        try:
            # 1) Recent chats
            try:
                from core.chat_history_cache import load_chat_history
                from core.interface_paths import get_recent_interface_paths

                recent = await get_recent_interface_paths(limit * 2)
                for item in recent:
                    if len(fragments) >= limit:
                        break
                    # Determine interface path
                    chat_path = item.get("interface_path")
                    if not chat_path:
                        continue
                    chat_path = str(chat_path)
                    try:
                        messages = await load_chat_history(chat_path)
                        # take up to 2 messages per chat (most recent)
                        taken = 0
                        for msg in reversed(list(messages)):
                            if not isinstance(msg, dict):
                                continue
                            text = msg.get("text")
                            sender = (
                                msg.get("sender_name")
                                or msg.get("sender_id")
                                or "unknown"
                            )
                            timestamp = msg.get("timestamp") or ""
                            if text:
                                # Filter irrelevant content
                                if not self._is_dream_relevant(text, sender):
                                    continue

                                snippet = text.strip()
                                if len(snippet) > 300:
                                    snippet = snippet[:300] + "..."
                                fragments.append(
                                    f"(chat:{chat_path} | sender:{sender} | {timestamp}) {snippet}"
                                )
                                taken += 1
                            if taken >= 2 or len(fragments) >= limit:
                                break
                    except Exception:
                        continue
            except Exception as e:
                log_debug(f"[grillo_dream] Failed to collect chat fragments: {e}")

            # 2) Random memories
            try:
                from core.db import get_conn_ctx

                async with get_conn_ctx() as conn:
                    async with conn.cursor() as cur:
                        await cur.execute(
                            "SELECT content FROM memories ORDER BY RAND() LIMIT %s",
                            (limit,),
                        )
                        rows = await cur.fetchall()
                        for row in rows:
                            mem = row[0]
                            if not mem:
                                continue
                            mem_str = str(mem)

                            # Filter irrelevant memories
                            if not self._is_dream_relevant(mem_str):
                                continue

                            if len(mem_str) > 300:
                                mem_str = mem_str[:300] + "..."
                            fragments.append(f"(memory) {mem_str}")
            except Exception as e:
                log_debug(f"[grillo_dream] Failed to collect memories: {e}")

            # Shuffle and return up to limit unique fragments
            if fragments:
                random.shuffle(fragments)
                # deduplicate while preserving order
                seen = set()
                out = []
                for f in fragments:
                    if f in seen:
                        continue
                    seen.add(f)
                    out.append(f)
                    if len(out) >= limit:
                        break
                return out
            return []
        except Exception as e:
            log_error(f"[grillo_dream] Error collecting fragments: {e}")
            return []

    def _build_dream_prompt(self, fragments: List[str]) -> str:
        """Return a compact prompt instructing the LLM to "dream" and reply with JSON diary action."""
        header = "[G.R.I.L.L.O. DREAM] You are dreaming. Below are fragments from recent chats and memories. Create a single evocative dream narrative based on these fragments. Do NOT output any text outside a valid JSON object."

        # Include fragments as bullet list
        body = "\n\nFragments:\n"
        for i, f in enumerate(fragments, 1):
            body += f"{i}. {f}\n"

        # Dream-only instructions (do not reuse chat observer guidance)
        instructions = (
            "\n\nINSTRUCTIONS (dream):\n"
            "- Generate a single, cohesive dream narrative (approx 150-400 words).\n"
            "- Rely SOLELY on the provided fragments; do NOT use memory_search or other tools.\n"
            "- RESPOND ONLY WITH VALID JSON following the exact format below (no prose outside JSON):\n"
            '{"actions": [{"type": "create_personal_diary_entry", "payload": {"interaction_summary": "Dream about [brief topic]", "personal_thought": "What lingered emotionally after the dream", "emotions": [{"type": "wistful", "intensity": 0.5}], "content": "..."}}], "meta": {"autonomous": true, "rationale": "Daily dream consolidation"}}\n'
            "- The diary 'content' should be the generated dream text (plain text).\n"
            "- 'interaction_summary', 'personal_thought', and 'emotions' are REQUIRED.\n"
            "- If you cannot generate a dream, reply with a JSON proposal explaining why (e.g., insufficient data).\n"
            "- Do NOT address or mention the WebUI or any system/internal labels (for example: 'webui', 'system', 'internal')."
        )

        return header + body + instructions


PLUGIN_CLASS = GrilloDreamPlugin
